### ISSUE TITLE
Make it possible to run CoreDNS as my dns server

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#15]
Dogfood time! I want to run CoreDNS as my DNS server. For this it needs to be able:
- Server DNS requests from db files (#5)
- Do DNSSEC query resolution
- Be able to slave zones (#8)
- Listen and send notifies, prolly related to (#8)

**Comment by miekg** [comment]
The todo list is now down to:
- [x] DNSSEC query resolution (NSEC will be thoughest)
- [x] response correctly when there is a wildcard in the zone (positive responses) (#62)
- [x] response correctly when there is a wildcard in the zone (nodata) (#62)
- [x] Slaving zones (#8)
- [x] check for slave zone periodically (obeying the SOA record) (#80)
- [x] notifies for master axfr (#56)

**Comment by miekg** [comment]
DNSSEC needs predecessor and successor in the tree implementation, `tree/tree.go` already has this, important thing is the closest encloser.

**Comment by miekg** [comment]
Some bits are left. It should be runnable, but is missing stuff like proper logging and good enough monitoring.

**Comment by miekg** [comment]
The wildcard stuff is not yet import, closed #80 and #56, but leaving #62 open as that still need fixing.
Closed the above TODO list.

I.e. this is looking good, should be running CoreDNS on my servers soonish.

**Comment by miekg** [comment]
This is running OK for 4 days now.
