### ISSUE TITLE
CoreDNS 1.7.0 Release tracking issue

### ISSUE THREAD

**Issue by miekg** [coredns/coredns#3945]
Let's release 1.7.0

iirc @yongtang had a (eager :-) ) PR for a 1.7.0 version upgrade somewhere, so we should merge, and release.

**Comment by yongtang** [comment]
The version bump is in https://github.com/coredns/coredns/pull/3782

**Comment by yongtang** [comment]
Item list:
- [x] Bump version to 1.7.0 (PR #3782)
- [x] Man page update (PR #3946)
- [x] Release note (PR #3947 and #3949)
- [x] Update 1.7.0 release note date (PR #3950)
- [x] Release

**Comment by yongtang** [comment]
@miekg @chrisohaver We are almost ready for 1.7.0 release, the remaining items I can think of, are
- PR #3950: Update 1.7.0 release note date
- Trigger automatic release.

Please add any other items that may need to be added before 1.7.0

**Comment by yongtang** [comment]
We are mostly ready to go. If there are no objections I am planning to trigger the release later today.

**Comment by yongtang** [comment]
Think the release timed out and could not deliver. @miekg Wondering if you can take a look?

**Comment by yongtang** [comment]
@miekg @chrisohaver Looks like it goes through, we have 1.7.0 release now! 👍

**Comment by miekg** [comment]
Thanks folks. I'm happy this is all working nicely.
